### PR TITLE
Add domains

### PR DESCRIPTION
**Pull request by tompec**
Hi @danhstevens, just to make sure, if a domain is wildcard, should it be only on the wildcard.json or in both wildcard.json and index.json lists?
Thanks.

### CODE REVIEW

**Comment by danhstevens** [comment]
Good question... My gut says, since wildcard.json is so new and few people will have implemented it, perhaps keeping it in both places is the best approach. What do you think?

**Comment by tompec** [comment]
Yes we should keep the domain in both places. I'll clean my pull request then you can merge.

**Comment by tompec** [comment]
Ok I think we're good to go :)

**Pull request merged**
