### PR TITLE
merge three other lists -- (EDIT... added another commit merging 13 other sources)

### PR DESCRIPTION
**Pull request by nivicentiu**
https://gist.github.com/michenriksen/8710649
https://gist.github.com/adamloving/4401361
https://github.com/martenson/disposable-email-domains

### CODE REVIEW

**Comment by danhstevens** [comment]
Thanks @nivicentiu so much! I'll try and get this reviewed today or early next week at the latest!

**Comment by danhstevens** [comment]
oof this has grown beyond what I can manually review (I always confirm each domain is from a valid disposable source). I also notice there are many non-disposable email domains added into this list now (ex: qq.com is an extremely popular free provider for China - it's not disposable). I'll work slowly towards identifying the legitimate disposable domains in this list and post them separately but it'll take some time.

**Comment by nivicentiu** [comment]
Ah... I missed that one... I was watching out to make sure the following aren't in the list, but I missed qq:
hotmail.com
zoho.com
gmx.com
gmx.es
gmx.us
yandex.com
otmail.com
mail.ru
**qq.com**
ymail.com
yandex.ru
bk.ru
126.com
163.com
sohu.com
sina.cn
139.com
o2.pl
o2.co.uk
bluewin.ch
poczta.onet.pl
snkmail.com
sneakemail.com

Let me know if if I can help with with the review process.
thanks

**Comment by danhstevens** [comment]
closing - not mergable

**Comment by nivicentiu** [comment]
Is this request still useful to you in the future? Do you want me to update it to make it mergeable, or is it too large?

**Pull request closed without merging**
