### PR TITLE
More domains

### PR DESCRIPTION
**Pull request by tompec**

### CODE REVIEW

**Comment by danhstevens** [comment]
`a.mail0.ga` and `1.mp-j.gq` both appear to be wildcard domains. They return `sss.pp.ua` with any subdomain (and without any subdomain).

**Comment by danhstevens** [comment]
Looks like some of those similar domains from previous commits should be wildcarded too. Example: https://github.com/ivolo/disposable-email-domains/commit/4d5095bfe5064e474eb01d39cab987c9f6789359#diff-9e743aa713dcae5405f290e3db88178bR12

**Comment by tompec** [comment]
Yep, I pushed the modification.

**Comment by danhstevens** [comment]
Awesome. Thanks!

**Pull request merged**
