### PR TITLE
Add wildcard domains

### PR DESCRIPTION
**Pull request by tompec**

### CODE REVIEW

**Comment by danhstevens** [comment]
Thanks! Can you let me know where these come from? Wasn't able to find MX records when doing wildcard lookups on them. Ex: `dig x.pp.ua mx` doesn't return any MX records whereas other wildcards tend to return MX records regardless of the subdomain.

**Comment by tompec** [comment]
Hi Dan, pp.ua is used by http://email-fake.com (and maybe other websites), and since they use a lot of subdomains and they generate new subdomains frequently, I figured it would be useful to have it on the list.
So it's not like 33mail.com, where every subdomains work, but you know that every email addresses coming from this domain will be junk.

**Comment by danhstevens** [comment]
Got it - perfect. And what's the story with `cu.cc`?

**Comment by tompec** [comment]
Used by https://discard.email/

**Comment by danhstevens** [comment]
Thanks! Sorry for the 20-questions. Just want to keep track of where these are coming in from. ~ Dan

**Comment by tompec** [comment]
You're welcome, thanks for the merge.

**Pull request merged**
