### PR TITLE
Remove cock.li-hosted domains from list

### PR DESCRIPTION
**Pull request by notpushkin**
As discussed in #405, those aren't really disposable. Most of them might look edgy and appeal to the corresponding kind of people, but still some of them are being used by real people out there (I use @airmail.cc / @firemail.cc addresses as my primary mailboxes actually :)

### CODE REVIEW

**Comment by hwvs** [comment]
Support

@danhstevens
https://github.com/ivolo/disposable-email-domains/issues/405#issuecomment-443895043

What about leaving the low quality domains in the blacklist, but removing the normal domains:
```cock.lu
airmail.cc
firemail.cc```

My github/primary email is actually an airmail.cc address. Cock has plenty of real users, mainly because the owner is trustworthy and takes privacy seriously.

**Comment by notpushkin** [comment]
@danhstevens Could you take a look and tell me what you think, please?

**Comment by danhstevens** [comment]
Thanks @notpushkin - There are merge conflicts but I'll resolve and push in an upcoming commit.

**Comment by danhstevens** [comment]
All set. Thanks for your patience.

**Comment by notpushkin** [comment]
Thank you so much!

**Pull request closed without merging**
