### PR TITLE
add/Anonaddy "Anonymous Email Forwarding"

### PR DESCRIPTION
**Pull request by Enaah**
- adds the domain `anonaddy.me` from the Service "Anonaddy (Anonymous Email Forwarding)" (anonaddy.com) to the wildcard Domains

### CODE REVIEW

**Comment by fareszr** [comment]
this is stupid, anonaddy is not a disposable mail service.

its a relay and its completely different thing, mail relays are completely valid email address when we as users don't want to expose our real emails to a website with dodgy privacy practices.

**Comment by Enaah** [comment]
Thanks for changing the tone in your comment.

I guess you're right. Will close this PR.

✌🏼

**Comment by fareszr** [comment]
yeah sorry about that!.

**Comment by Enaah** [comment]
🤝 🙂

**Pull request closed without merging**
