### PR TITLE
add hey.com

### PR DESCRIPTION
**Pull request by tuptuptuu**
add hey.com
7BCBF776-00DE-4A1B-A8D9-79D5D3D9B4B1

### CODE REVIEW

**Comment by bxio** [comment]
I for one don't think hey.com should be added, the accounts are send-limited and the paid service has lots of legitimate users. https://hey.com/pricing/

**Comment by troytoman** [comment]
Reaching out here from the hey.com team. We do have limits on these temporary accounts and they are a small fraction of our users. All temp addresses follow a consistent format of 12 digits with dashes separating each group of 4 digits. So, temporary addresses are all of the formant ####-####-####@hey.com

We are looking at further differentiating these with a subdomain but this is not yet in place. Would be happy to work with folks to limit the impact of these accounts while not penalizing paid HEY users.

**Comment by danhstevens** [comment]
Thanks everyone for your input on this issue. Since HEY is a legitimate email service that offers disposable addresses as one of its features, it's entire domain shouldn't be listed as disposable. Yahoo offers a similar disposable feature but obviously listing yahoo.com wouldn't go over too well :)

Closing this issue. Perhaps we can look at adding separate user-side expressions to detect disposable addresses on domains like Yahoo and HEY.

**Comment by bxio** [comment]
In case anyone wasn't aware, @tuptuptuu is a throwaway account seemingly created solely for the purpose of adding the hey.com domain to disposable email lists. See similar pull requests this person has filed: 

* https://github.com/andreis/disposable/pull/50
* https://github.com/martenson/disposable-email-domains/pull/244
* https://github.com/wesbos/burner-email-providers/pull/226
* https://github.com/micke/valid_email2/pull/153

As well as [this twitter thread](https://twitter.com/dhh/status/1277805249147752449) from @dhh.

**Pull request closed without merging**
