### PR TITLE
updated the list w/ ones we added @koding

### PR DESCRIPTION
**Pull request by sinan**
Since we're giving free resources to developers we're often tried for abuse. I cross checked with your list and made a filemerge with what we already had.

Apparently, on top of your list, we added 200+ domains over time. Hoping to have this merged and maintained in one place.

### CODE REVIEW

**Comment by danhstevens** [comment]
Hey thanks for these! I will go over each one but I see a couple that should be removed:

126.com
139.com
163.com

These are popular chinese domains that offer free email accounts. Addresses from these domains might be seen as low-quality by some, but these are not "disposable" email service providers like mailinator, etc.

**Comment by sinan** [comment]
Ah good to know, thanks. I'll update the PR. Once you check them all please let me know if there are other legit domains.

**Comment by danhstevens** [comment]
Alright I've finished looking through the commit. The following should be removed:

- 126.com
- 139.com
- 163.com
- example.com
- hushmail.com
- lavabit.com
- qq.com
- yahoo.com.ph
- yahoo.com.vn

Once those changes are pushed let me know and I'll merge! Thanks again!

**Comment by sinan** [comment]
updated :+1:

**Comment by danhstevens** [comment]
Boom. Done. :)

**Comment by sinan** [comment]
Awesome thanks. 

In the meantime @sent-hil just updated me with another list of [171 domains (gist)](https://gist.github.com/sinan/bf5a8ede81342f6a98e6). I can send that as another PR, however most of them look legit because they use a freedns service. What do you think we should do, do they belong here?

**Comment by danhstevens** [comment]
The criteria I use is if the domain name (and/or its MX records) point to a service where you can get a throw-away address (typically without setting a password or providing any other user information) then it's disposable. Otherwise, if it's a free domain or even a low quality but private domain, I say we leave it off the list.

PR-away with that in mind! And thanks again!

**Comment by sinan** [comment]
alright, maybe on a later PR then.

**Pull request merged**
