### PR TITLE
eod

### PR DESCRIPTION
**Pull request by joanliu**

### CODE REVIEW

**Comment by joanliu** [comment]
any way we can get these automated? I know they're tricky, but when i go on vacation for a week, they appear never to be added, as i manually check every couple of days.

**Comment by GeroldSetz** [comment]
> 
> 
> any way we can get these automated? I know they're tricky, but when i go on vacation for a week, they appear never to be added, as i manually check every couple of days.

Sure! Why not just taking over my data from https://github.com/GeroldSetz/emailondeck.com-domains?
It's automated ;-)

**Comment by tompec** [comment]
@joanliu Enjoy your vacation and thanks for your contributions. I'll try to check EOD.
@GeroldSetz I think at this point everyone knows your website... We'd be happy if you could contribute to the list though.

**Comment by joanliu** [comment]
Hey @GeroldSetz, I'm happy to provide insight on why we switched away from using your service as our primary email verification service - what's the best way to get in touch?

**Comment by GeroldSetz** [comment]
> 
> 
> Hey @GeroldSetz, I'm happy to provide insight on why we switched away from using your service as our primary email verification service - what's the best way to get in touch?

@joanliu that would be great to understand, indeed! Please drop me a line via https://www.block-disposable-email.com/cms/about/contact/ and I'll get in touch.

**Comment by danhstevens** [comment]
@joanliu I'm open to ways to automate this but there are two challenges:

1) Since I'm not the repo owner I can't make admin changes to add continuous integration, etc. We might need to move this to a new repo
2) I currently manually review submissions because many people try to add non-disposable domains to this list. You and the other regular contributors make solid contributions but other contributions need to be vetted.

Anyways - open to any suggestions!

**Pull request merged**
