### PR TITLE
Add more domains from mytemp.email

### PR DESCRIPTION
**Pull request by tompec**

### CODE REVIEW

**Comment by danhstevens** [comment]
For several of these wildcard additions I can only find one instance that is actually tied to a valid MX record. For example, `l5.ca` seems to only have a mytempemail on the subdomain `e.l5.ca`. The parent domain seems to have a different MX record. Some of these also seem to use hotmail, etc for the main domain and only have one subdomain that is used for mytempemail. For these, perhaps the subdomain (ex: `e.l5.ca`) should be added to index.json and when/if it becomes apparent multiple subdomains are in use it should be added to the wildcard.json?

**Comment by tompec** [comment]
Well, let me explain my view. If disposable domains were a virus: If a body (the domain) is infected, I kill the host. If a leg is infected (a subdomain) I kill the host too, because I don't want to take any risk 😂  So, I prefer to ban a domain even if there's only one subdomain, because in my mind, there's propably only 1% chance that the domain will serve as a legitimate email provider, than to ban only the subdomain and take the risk to get more spam from another subdomain.
I'm ok with your idea, but that means that we will have to check the index.json list everytime we add a wildcard domain, to see if a subdomain already exists with the same domain, etc...
It's a great level of perfection to avoid false positive, but if we do so, we should also check every domains on the list, to make sure they are still disposable domains and not reused for legitimate websites...

**Comment by danhstevens** [comment]
Good points. I think by that logic, however, we should ditch index.json and just make all domains wildcards. I do think there are _some_ domains out there and I'd hate to put on a wildcard naughty list when the domain owner merely donated one of their subdomains to a disposable email service.

For now I vote we keep subdomains in index.json, and only add wildcards for domains that we confirm have multiple subdomains which direct mail to a disposable service. If you have > 1 subdomain that you're pointing to a disposable service, then at that point I'd say you're fair game to be a wildcard.

We could also potentially write a script that identifies which list a domain should be on (check to see if there are other subdomains that warrant it being removed from index.json and moving to wildcard.json, and testing for multiple/nested mx records, etc).

That's my perspective. There are some services that rely on this list that could lose money if we advise them to disregard an email address. Although this is open-source software and we don't offer any warranties, I'd want to avoid shooting too much from the hip.

What say yee?

**Comment by tompec** [comment]
Yeah that works for me 👍 Can you make that script?

**Comment by danhstevens** [comment]
Yeah I'll work on that. In the meantime, if you'll prune those wildcard domains for which only have 1 known subdomain (and replace with their subdomains in index.json) I'll get this pulled in.

**Comment by danhstevens** [comment]
Fixed via https://github.com/ivolo/disposable-email-domains/commit/e22eadc06b87c36b3bed1097115177f5e46e09e3

**Pull request closed without merging**
