### PR TITLE
More domains

### PR DESCRIPTION
**Pull request by tompec**

### CODE REVIEW

**Comment by danhstevens** [comment]
`vuygold.tk` and `lapeterblog.cf`don't appear to be registered domains.

**Comment by danhstevens** [comment]
What are your thoughts on my previous comment about the unregistered domains in this commit?

**Comment by tompec** [comment]
Oops, missed that comment. Sorry about that, I'll remove them.

**Comment by danhstevens** [comment]
Sweet - thanks!

**Pull request merged**
