### PR TITLE
Adds PHP class for facilitating usage in PHP projects

### PR DESCRIPTION
**Pull request by adhocore**
Please let me know if the namespace `Ivolo\DisposableEmail` and class `Domain` doesnt make sense and needs to be revised

### CODE REVIEW

**Comment by adhocore** [comment]
closing due to indifference. feel free to open &/or ping

**Comment by danhstevens** [comment]
Hi @adhocore sorry for not circling around to this in a timely manner and thanks for your work on this. To keep things simple it'd be best practice to keep this repo language-agnostic but putting your code in a separate repo that uses this repo as a dependency would be well received I believe.

**Comment by adhocore** [comment]
alrite no worries. i will still send a PR here to link up the new repo 😁

**Comment by gabiudrescu** [comment]
@adhocore have you created the new repo? 

if you haven't, would you like to delegate this?

**Comment by adhocore** [comment]
not yet, almost forgot it. so how do we delegate on this:
- create new repo
- or, revive this PR?

**Comment by pidario** [comment]
I don't know of or can be of any interest to tour, but I created a repo for Go language: https://github.com/pidario/disposable

**Pull request closed without merging**
