### PR TITLE
xztech.me

### PR DESCRIPTION
**Pull request by GeneGeren**
xztech.me

### CODE REVIEW

**Comment by danhstevens** [comment]
hi thanks so much for these! if you resolve the conflicts I'll get this reviewed and pulled in.

**Comment by GeneGeren** [comment]
Hi, I've resolved the conflicts. Please review.

**Comment by danhstevens** [comment]
The commit has grown fro 800 changes to 17,000 making it not easy to review. I'll take a look at your first commit `5c7fe7a` and pull confirmed domains from that.

**Comment by danhstevens** [comment]
closing - not mergeable

**Pull request closed without merging**
