### PR TITLE
Add legitimate email whitelist

### PR DESCRIPTION
**Pull request by Gtoffo**
_V2 based on @danhstevens comments on previous PR._

**Proposal**:
Added a complete list of legitimate email providers that can be useful for whitelisting legitimate domains. As this repo is well maintained it would be useful to be able to contribute also this list and edit it as necessary.

The current initial list is based on a list found here: https://gist.github.com/tbrianjones/5992856

Being on gist contributing to this list is not practical so it would be better to include it in a well maintained git repo.

Thanks for the great work!

**Comments on second PR:**
The point here is that the whitelist shouldn't overlap in any way with the other lists as it represents legitimate email providers (such as gmail.com).

The list I used in previous PR was an expanded one I found but looks like it was way too permissive. I've switched as base to the original list of whitelisted domains: https://gist.github.com/tbrianjones/5992856
It's the most starred version I could find (some stuff is missing but once we have it in a repo we should be able to collectively maintain it).

I've checked the original list and it contains no duplicates compared to the temp email list.

I think it would be useful to keep both lists on the same repo as it would be easier to maintain.

Thanks!

### CODE REVIEW

**Comment by Gtoffo** [comment]
Hey @danhstevens (or other maintainers) let me know what you think about this and if you don't intend to merge it.

Thanks!

**Comment by tompec** [comment]
If I may put my two cents in this: aren't all emails that are not in this repo considered as legitimate by default?

**Comment by Gtoffo** [comment]
Hey @tompec thanks for the reply.

An example of use would be if you are checking for duplicates in email domains (e.g. check upon registration to a service if the domain is already registered) the "legitimate providers" list will allow you to whitelist domains that will necessarily be duplicated (e.g. gmail).

In conjunction with the blacklist it will allow you to verify that only real domains are registered and that no duplicates are created or somebody could create a "personal" temporary email domain.

This is just one example of how this could be useful but I hope it makes sense.

Thanks!

**Comment by danhstevens** [comment]
Hey @Gtoffo thanks again for this contribution. I don't think a whitelist is something I'm equipped to manage within this disposable domain repo. I do encourage you to consider posting this as a standalone project! Thanks again and all my best!

**Pull request closed without merging**
