### PR TITLE
adding rcasd.com

### PR DESCRIPTION
**Pull request by irvin**

### CODE REVIEW

**Comment by danhstevens** [comment]
Thanks Irvin. Could you let me know the source of this domain? MX Records seem to point to linode so wasn't able to determine that way.

**Comment by danhstevens** [comment]
Unable to locate source. Closing.

**Comment by danhstevens** [comment]
ah - was able to find on: https://10minutemail.net - will merge

**Comment by irvin** [comment]
great, thanks!

**Pull request merged**
