### PR TITLE
new wildcard domain

### PR DESCRIPTION
**Pull request by molayli**

### CODE REVIEW

**Comment by danhstevens** [comment]
I see `bccto.me` is definitely disposable but wasn't able to find any subdomains of `bccto.me` that accept email which would necessitate a wildcard entry. Can you point me in that direction?

**Comment by GeroldSetz** [comment]
Www.bccto.me is one of the subdomains provided.

**Comment by molayli** [comment]
mail.bccto.me , www.bccto.me , m.bccto.me are all the same,  for me this is enough to block anything from this domain .

there is more domains inside the dropdown in the middle right  but I didn't test them :neutral_face: 

```
11163.com
jnpayy.com
4057.com
sohus.cn
zhewei88.com
a7996.com
chaichuang.com
dawin.com
zymuying.com
ytpayy.com
3202.com
svip520.cn
cr219.com
juyouxi.com
haida-edu.cn
cuirushi.org
dongqing365.com
zhaoyuanedu.cn
huangniu8.com
dhy.cc 
```

**Comment by danhstevens** [comment]
The only domain that has an MX record is bccto.me. The others appear to be related to the website (and mail.bccto.me is the mx record itself). Technically they're all the same IP address so they all accept a port 25 connections but sending email to any of those other domains don't appear in your bccto.me inbox so for now I'll close this PR. If they do start accepting mail on these subdomains I'll reopen and accept. Thanks!

**Pull request closed without merging**
